# Generated by Django 6.1 on 2026-08-09 06:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='id',
            field=models.CharField(default=api.models.gen_road_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
