# Generated by Django 6.1 on 2026-08-11 17:10

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sosalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=api.models.gen_review_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_reviews', to='api.road')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
