# Generated by Django 6.1 on 2026-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=15),
        ),
    ]
